### ISSUE TITLE
Issue with actions/checkout@v2

### ISSUE THREAD

**Issue by ahaverbuch** [phips28/gh-action-bump-version#10]
Thanks for a useful action!

We noticed this in one of our projects; https://github.com/actions/checkout is called before phips28/gh-action-bump-version, and that worked great in actions/checkout@v1 of it. 

In actions/checkout@v2, they changed to no longer use a detached HEAD at first, instead to use a branch directly; this causes gh-action-bump-version to fail.

Appears this is because gh-action-bump-version is trying to make the same commit twice (once on the initial branch, and once when checking out the second branch) - as those are now the same. (error line is here: https://github.com/phips28/gh-action-bump-version/blob/v5.0.19/index.js#L55 )

We got the same error @benitazhang mentioned here https://github.com/phips28/gh-action-bump-version/commit/be1eb84449c580c17675df53ddb5edd92325d977#commitcomment-36934730 - failing when running `git commit -a -m ci: version bump to [version]` 

(it is not related to the quotes change though, as that change works fine with actions/checkout@v1 - thanks for fixing that!)

**Comment by phips28** [comment]
nice find.
but I am not sure how to solve it to work for v1 and v2 (I dont want to break checkout@v1 usages).
Do you have any idea?

**Comment by ahaverbuch** [comment]
maybe skip the first part if on a detached HEAD? not sure that whole section is needed on v2.

Something like this `git rev-parse --abbrev-ref --symbolic-full-name HEAD` should tell you if you are on HEAD or a branch.

**Comment by zkoppert** [comment]
Just wanted to note that I was having trouble getting this action to work but saw @ahaverbuch note here about v1 vs v2 and that helped me. Thanks for opening the issue! This saved me lots of time debugging.

**Comment by ffMathy** [comment]
V2 support is quite crucial.

**Comment by sarink** [comment]
Most other actions nowadays don't support checkout v1, making this lib incompatible and impossible to integrate in many workflows. Is there any workaround for using this with v2?

**Comment by phips28** [comment]
ok, I finally had time to fix that :)
https://github.com/phips28/gh-action-bump-version/pull/14
