### ISSUE TITLE
Configurable author (email and name)?

### ISSUE THREAD

**Issue by dkershner6** [phips28/gh-action-bump-version#101]
We have security downstream to prevent non company authors from committing and deploying, so the version bump just sets off the security. How difficult would it be to make this information editable?

Thank you!

**Comment by phips28** [comment]
can you set a env var?

check code: https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L90
```
process.env.GITHUB_USER
process.env.GITHUB_EMAIL
```

**Comment by dkershner6** [comment]
Totally worked, thank you!
