### ISSUE TITLE
Custom commit actor

### ISSUE THREAD

**Issue by jacobhq** [phips28/gh-action-bump-version#110]
Hello, is there a way to customise the name of the commit actor? I've looked through the README and couldn't find anything about it.

**Comment by phips28** [comment]
Yes, set the ENV var in your action file:
```
process.env.GITHUB_USER
process.env.GITHUB_EMAIL
```
https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L122

**Comment by jacobhq** [comment]
Ok thanks, closing this now.
