### ISSUE TITLE
Tags are not being created/pushed

### ISSUE THREAD

**Issue by boris-remo** [phips28/gh-action-bump-version#114]
I tried out this action in two different repos and got the same result - package.json is bumped as expected, but no tag is added.

![image](https://user-images.githubusercontent.com/81965134/127308010-dfa445bb-d93b-49ed-b1db-8f8e094ae204.png)

My workflow - https://github.com/boris-remo/lerna-playground/blob/master/.github/workflows/bump.yml
Pushed commit - https://github.com/boris-remo/lerna-playground/commit/47999d79f5286b0adc27ebb2c677bb7575a56693
No new tags were created - https://github.com/boris-remo/lerna-playground/tags

In the workflow logs I see that a new tag was generated and logged - https://github.com/phips28/gh-action-bump-version/runs/2970462068?check_suite_focus=true
![image](https://user-images.githubusercontent.com/81965134/127308181-ca03509c-1b2c-42bf-89fc-dcc4443913b5.png)

**Comment by phips28** [comment]
That's the expected behaviour when you `skip-tag: true` in your action: https://github.com/boris-remo/lerna-playground/blob/master/.github/workflows/bump.yml#L24

Please remove that skip tag config and try again :)

**Comment by boris-remo** [comment]
This is what happens when you copy paste without reading the code...
Thanks @phips28 !
And nice work on this repo!
