### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Spiegelberg** [phips28/gh-action-bump-version#122]
npm notice 
  npm notice New minor version of npm available! 7.6.3 -> 7.21.0
  npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.21.0>
  npm notice Run npm install -g npm@7.21.0 to update!
  npm notice 
  npm ERR! code ERR_SOCKET_TIMEOUT
  npm ERR! errno ERR_SOCKET_TIMEOUT
  npm ERR! request to https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz failed, reason: Socket timeout
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2021-08-24T11_15_26_400Z-debug.log
  The command '/bin/sh -c npm ci --only=production' returned a non-zero code: 1
  
Error: Docker build failed with exit code 1

**Comment by JasonasIgn** [comment]
Bump

**Comment by donnes** [comment]
It's happening

**Comment by Spiegelberg** [comment]
all good, i fixzed runtime to nodejs14 in my app.yaml, and everything worked out good. sorry for posting the issue

**Comment by phips28** [comment]
Yes, bump to node14 in your action.yml helps.
https://github.com/phips28/gh-action-bump-version/pull/123
