### ISSUE TITLE
I'm having an issue committing to a protected branch

### ISSUE THREAD

**Issue by s1m2** [phips28/gh-action-bump-version#125]
Hi, I'm trying to use this action in a repo configured with a protected main branch that requires 2 PR reviews and testing checks to run.

I have tried to create a personal token to replace the GITHUB token, I'm still getting the same result.

![issue](https://user-images.githubusercontent.com/4314513/133579387-5a749665-028e-4778-ad26-b480dbee488f.PNG)

My action

![Capture](https://user-images.githubusercontent.com/4314513/133579544-187f5135-644d-455f-b4c7-9b3f7d139b15.PNG)

**Comment by the-maazu** [comment]
The protected branch is doing exactly what you want which is to protect against 'write' from all who have write permision, token included.

https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/5
