### ISSUE TITLE
Create target-branch if it doesn't exist

### ISSUE THREAD

**Issue by melody-universe** [phips28/gh-action-bump-version#129]
Quoted from issue #70:

> I might be doing something wrong, but if I set the target-branch property, I get the following:
> 
> ```
> ✖  fatal     Error: Command failed: git checkout development 
> error: pathspec 'development' did not match any file(s) known to git.
> 
> 
>     at makeError (/node_modules/execa/index.js:174:9)
>     at /node_modules/execa/index.js:278:16
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async /index.js:99:5
> ```

Ideally, this action should try to fetch `target-branch`, and if it doesn't exist, create it.

**Comment by dschoon** [comment]
+1 on this issue...

My `dev` branch has restrictions to merging and requires 1 PR. So the merge fails. But I also can't push to a target branch dynamically due to this issue.

I think ideally it should push to a new branch and open a PR.

**Comment by phips28** [comment]
Maybe you want to use `skip-push: true` https://github.com/phips28/gh-action-bump-version#skip-push (does not commit nor push any tags) and then create your own script to do what you need.
