### ISSUE TITLE
Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by NitzanShifrin** [phips28/gh-action-bump-version#131]
Since the last version, I'm getting this error
![image](https://user-images.githubusercontent.com/42731841/135256890-ae45e60f-4f9d-46ed-a1e6-940a70002a62.png)

I saw that the new version has something to do with it

The NPM TOKEN is saved as an organization secret and was working great till 7 days ago

This is the code
![image](https://user-images.githubusercontent.com/42731841/135257505-1dbfd942-d24b-420f-86a5-1181dc85ae73.png)

**Comment by phips28** [comment]
can you lock the version of the action to 8.x? to see if there were breaking changes at 9.x

**Comment by NitzanShifrin** [comment]
@phips28 
Locking to v8.3.3 works

![image](https://user-images.githubusercontent.com/42731841/135258775-bd1be293-d4d6-4cab-b1fc-6ecf743c74c5.png)

**Comment by phips28** [comment]
@melody-universe do you know if the new version from you PR needs some stuff to support this?

**Comment by melody-universe** [comment]
It looks like [this line](https://github.com/phips28/gh-action-bump-version/blob/0447b8c469a6ddcc66f12ae4c2fd96317eeb9ac6/index.js#L143) might be the culprit:
```javascript
await runInWorkspace('npm', ['version', '--allow-same-version=true', '--git-tag-version=false', current]);
```

One of the dependencies we removed was [execa](https://github.com/sindresorhus/execa), which was previously being used to execute npm / git commands. There might be something in the `runInWorkspace` function that doesn't quite cover the functionality that execa was providing.

I'm going to try to replicate this in my tests and get some information on where `NPM_TOKEN` is supposed to be coming from and why it's not working the way it used to.

**Comment by melody-universe** [comment]
I'm having difficulty replicating the issue.

@NitzanShifrin, you said you have `NPM_TOKEN` registered as an organization secret. Are you doing anything to pass that token into this job? I couldn't find anything in the code that attempts to use the `GITHUB_TOKEN` environment variable as an `NPM_TOKEN`, and I don't see anything in the yaml you provided that passes `${{ secrets.NPM_TOKEN }}` as an environment variable or parameter to any of your actions.

As another test, I might fish up a previous version of this action I built that stores the `node_modules` folder in the repository, which would then use execa the same way it did previously, just to confirm or rule out that line as our issue.

**Comment by NitzanShifrin** [comment]
@melody-universe 
The GitHub token is used to push into a protected branch (by the way, I would add this to the main readme, it took me some time to find a solution, and it is probably a common scenario.)

'if you need to push into a protected branch, create a token with administror privileges and use it as GITHUB_TOKEN', or something like that

Seems like adding  NPM_TOKEN: ${{ secrets.NPM_TOKEN }} to the env variables solved the problem.
for some reason, this didn't happen in the v8 version.

Thanks for your quick help!

**Comment by melody-universe** [comment]
@NitzanShifrin
That's really interesting. I wonder if there is an issue with the `.npmrc` file? Admittedly, I don't know too much about it and how it works, but a brief search of the error you were seeing would indicate that it's relevant.

I'm glad you were able to resolve it on your end, but if/when you get a moment, would you be able to create a public repo so that we can troubleshoot it? Would be great to have an idea as to exactly what caused it so we can explain why it broke as a result of the changes, or better yet, add a fix to v9 to resolve whatever caused the break.
