### ISSUE TITLE
Use pre-alpha as default

### ISSUE THREAD

**Issue by NitzanShifrin** [phips28/gh-action-bump-version#137]
We have several GitHub actions for deployments.
we use the version bump in every single one of them, but we want to use the option for pre-alpha and alpha.

Is there a way to add custom / pre-alpha + alpha to the end of a version without a previous commit including those words?

I've tried to use the commit message of the version bump itself but it did not work

    - name:  'Automated Version Bump'
      uses:  'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.CD_DEPLOYMENT_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        minor-wording:  'MinorBump'
        major-wording:  'MajorBump'
        skip-tag:  'true'
        commit-message: 'CI: pre-alpha version bump {{version}}'
        
 Any chance you make it to work with the commit-message as-well / add a variable of customVersion and then it could be {{package.json version}}-customVersion

**Comment by phips28** [comment]
I dont fully understand your final goal.
commit message with pre-alpha in it? (this should work as you configured it, to customize your commit-message https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L26)

Maybe I need a better example of what you are trying to solve. Or you check the code and see if you can do it 😉  (the script is short)

**Comment by NitzanShifrin** [comment]
@phips28 First of all, your response time is off the charts 💯.
Looked into the script, I thought that setting rc-wording to empty, and pre-id to 'alpha' will resolve in 1.2.7-alpha-0
![image](https://user-images.githubusercontent.com/42731841/142771154-863fdfb4-a51c-49c5-80dd-5726e7de8b58.png)
![image](https://user-images.githubusercontent.com/42731841/142771167-3cc35b2c-ce89-4c39-b196-ab651c378788.png)
but the result was 1.2.7-0

**Comment by NitzanShifrin** [comment]
So, I think I figured the problem.

in order to write, 1.2.7-aplha-0
I need this code to be executed
![image](https://user-images.githubusercontent.com/42731841/142772907-82e9d96c-9433-4ec6-90ff-51664359b876.png)

In order for this code to be executed, I need to pass this code without entering
![image](https://user-images.githubusercontent.com/42731841/142772926-d5993599-93b8-47d9-ad79-026e54a1deac.png)
so I need preReleaseWord to be empty.

But, if I send preReleaseWord as empty, this code makes it [''] array with empty string
![image](https://user-images.githubusercontent.com/42731841/142772999-da804595-8f52-41e9-8938-47802083b352.png)

array with empty string makes my code fall in the first condition
![image](https://user-images.githubusercontent.com/42731841/142773010-14f9a211-e5c4-41b9-a900-2c784d98e6ae.png)

And then my preReleaseWord is '' and this is why I didn't see the alpha.

What parameters should I set if I want to get 
CHAGINGVALUE = alpha / preAlpha / anything I wanta
x.x.x-{CHAGINGVALUE}-x

**Comment by phips28** [comment]
Good finding. 
Can you test with the latest master?
> added check for empty `INPUT_RC-WORDING`

**Comment by NitzanShifrin** [comment]
I think this change is no good
even if preReleaseWords is [], it still falls short on line 92
try to change     preReleaseWords !== '' 
to     preReleaseWords != '' 

(remove 1 of the equal signs to make it equal)

**Comment by phips28** [comment]
changed it again: https://github.com/phips28/gh-action-bump-version/commit/0f4358dcdd0e1a4c5d241be6c44805920ef413de

**Comment by NitzanShifrin** [comment]
Seems great!
I'll keep you updated if I see any other issue
Thanks for the quick fix!
