### ISSUE TITLE
Bump a version without doing a git commit

### ISSUE THREAD

**Issue by emagnier** [phips28/gh-action-bump-version#138]
Is there a way to bump the version of a `package.json` without doing a git commit? A possible `skip-commit: true` option?

In our workflow and after the automated bump, we build and generate submodules that will be then published as standalone NPM packages. And these submodules have the same NPM version as the main NPM project. 

And of course, if the build is failing, we do not want to commit anything. The idea is to commit (in a last step) the updated NPM version only if everything as been well built and tested before.

Thank you!

**Comment by emagnier** [comment]
Probably, if `skip-commit` is `true`, it would make sense to have the `skip-tag` also set to `true`?

So maybe we could call it `skip-tag-and-commit`?
What do you think?

**Comment by phips28** [comment]
if you provide a PR with a skip-commit: boolean, I am happy to merge it ;)

**Comment by emagnier** [comment]
Sure! I'll try to do it in the coming days.
