### ISSUE TITLE
Skip push

### ISSUE THREAD

**Issue by rosshamish** [phips28/gh-action-bump-version#141]
Hey there, thanks for the action. I'm trying to use the `push: false` capability, but I can't tell if I misunderstand its intent or if it's not working properly. Far as I can tell, there's 4 things that happen in order:
1. Decide on the new version
2. Update package.json with the new version
3. Commit (and maybe tag)
4. Push

The README says *"Set false you want to avoid pushing the new version tag/package.json
"*, which I understood to mean that steps 1-3 would still happen, and we would skip just the push in step 4. But the actual implementation+behavior seems to early return after step 1, totally skipping the package.json update, commit, **and** push. 

https://github.com/phips28/gh-action-bump-version/blob/96694d8fde2ceec374b3a631bb50bbc3911a5385/index.js#L113-L118

My usecase is to bump the version and commit, but then wait until later to push the commit b/c of contention on the main branch. It's a monorepo with multiple build artifacts with their own versions, so a single PR merge can trigger multiple version bumps.

Would you be open to a PR to fix this behavior? I have a tentative change locally that I'm using anyway. Let me know, thanks!

**Comment by phips28** [comment]
You are right. Everything gets skipped here. 
I can remember that was a PR of someone else. But not 100% sure why we implemented it that way 🙈

**Comment by rosshamish** [comment]
Cool cool. Alright if I put up a PR in the next couple days with the change?

**Comment by phips28** [comment]
Yes! But make sure it does not break existing behavior.

**Comment by rosshamish** [comment]
So, the existing `push: true` behavior makes this action do... well, nothing. If I was to change the behavior to do steps 1-3 from my original comment, but skip the push, that in theory would break someone whose workflow depends on the existing behavior of being a no-op. Aka, if anyone has a workflow which uses `push: true`, they would suddenly be getting their package.json modified, a local git commit, and a local git tag.

I'm not sure it's reasonable for someone to be depending on the flag in that way, but to be extra safe I'll propose this: add a new flag `skip-push`, to match the naming of the new one from #139 . Give it the expected behavior as described in the previous comments, and then mark the `push` flag as deprecated. If you decide to release a breaking/major version at some point down the line, you could remove it entirely.

**Comment by phips28** [comment]
ok sounds good!

**Comment by rosshamish** [comment]
Hey, I went ahead with this approach and opened #143. 

I used the end to end test suite to verify the behavior, although I had to make a bunch of changes to get them running. I see there's #128 tracking that test suite, I might tag on there and contribute some of my changes to get them running.

**Comment by phips28** [comment]
thx!
