### ISSUE TITLE
auto write plugin file in cypress

### ISSUE THREAD

**Issue by hern12** [phips28/gh-action-bump-version#145]
I have a cypress test folder and after bump, it auto write my file, and app was broken when compile. How can I bump only package.json.?

**Comment by phips28** [comment]
I dont fully understand your issue. I never worked with cypress.

This package only bumps package.json

**Comment by hern12** [comment]
<img width="1248" alt="Screen Shot 2565-01-17 at 11 03 35" src="https://user-images.githubusercontent.com/13413078/149706406-ac8315c4-4a28-45e9-82ed-af26c31aa827.png">
I saw this after bump. when I comment the code and bump again it will appear again

**Comment by phips28** [comment]
I dont know why this gets added automatically. and I don't know about cypress.

The plugin just does a `npm version patch` and then some git commit and git push. Maybe you have some hooks in your package json on those events.
Check this by executing the commands manually in the CLI.

**Comment by hern12** [comment]
thank you :)
