### ISSUE TITLE
Producing invalid tags

### ISSUE THREAD

**Issue by jblevins1991** [phips28/gh-action-bump-version#159]
I ran into a situation where the tag name that is being constructed is not valid. This is in a lerna monorepo with yarn workspaces. For some reason the `name` field of that package's `package.json` is being used when the tag is constructed. This is not the same experience that I saw a couple of weeks ago. Any help to work around this would be appreciated.

```
Run phips[2](https://github.com/nun/ya/biz/ness)8/gh-action-bump-version@master
  with:
    major-wording: MAJOR,cut-major
    minor-wording: add,Adds,new
    patch-wording: patch,fixes,fix,bugfix,chore
    tag-prefix: TAG-
    rc-wording: pre-alpha,pre-beta,pre-rc
    skip-tag: false
    skip-commit: false
    skip-push: false
    default: patch
    preid: rc
    bump-policy: all
    push: true
  env:
    OPAQUE_TOKEN: ***
    OPAQUE_TOKEN: ***
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    OPAQUE_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    PACKAGEJSON_DIR: packages/package
    GITHUB_TOKEN: ***
commit messages: [ 'fix: added github token to version bump (#142)\nundefined' ]
config words: {
  majorWords: [ 'MAJOR', 'cut-major' ],
  minorWords: [ 'add', 'Adds', 'new' ],
  patchWords: [ 'patch', 'fixes', 'fix', 'bugfix', 'chore' ],
  preReleaseWords: [ 'pre-alpha', 'pre-beta', 'pre-rc' ]
}
version action after first waterfall: minor
version action after final decision: minor
currentBranch: main
current: 0.22.2 / version: minor
current: 0.22.2 / version: minor
v0.2[3](https://github.com/nun/ya/biz/ness).0
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✖  fatal     fatal: 'TAG-@npm-domain/package-name
v0.[23](https://github.com/nun/ya/biz/ness).0' is not a valid tag name.
```

**Comment by jblevins1991** [comment]
How would I go about locking to a particular version? Can I change `@master` to a tag or does it have to be as specific as a commit hash?

**Comment by jblevins1991** [comment]
I figured it out! Thank you for the direction. I will look through the code and submit a PR to convey the version number to make this a bit easier other developers in the future.

**Comment by edunuti** [comment]
@jblevins1991 Did you get around to submitting a PR for this issue by any chance, or how did you overcome this issue? Am experiencing something similar where if `PACKAGEJSON_DIR` is set, the package name is appended to the returned version tag.
