### ISSUE TITLE
v7.0.2 doesn't `git commit` the updated package.json file

### ISSUE THREAD

**Issue by syclik** [phips28/gh-action-bump-version#16]
This used to work and when it executed today, it didn't.

I've set up a minimal working example here: https://github.com/syclik/test-action

I've done a little debugging:
- the action correctly checks out the branch
- the action correctly runs npm version and prints out the old and new version
- the action **does not** git add the updated `package.json` file
- the action correctly adds a git tag with the new version

To test that, I ran the action on a new repo. I don't know the permissioning on GH Actions well enough, so just in case you can't see the details here: https://github.com/syclik/test-action/runs/559503561?check_suite_focus=true

![image](https://user-images.githubusercontent.com/425751/78412522-a6844880-75e1-11ea-84eb-589ac3635a69.png)

(note the `git status` step where it says that `package.json` is modified)

---

P.S. Thank you!

**Comment by phips28** [comment]
Hi @syclik,
thx for reporting. 
Today we had a major update to 7.x with breaking changes were we removed the support of "actions/checkout@v1". I guess you have not fixed your version and just used the master ;)

I added the v1 support again. So please checkout the new v7.0.4 https://github.com/phips28/gh-action-bump-version/releases/tag/v7.0.4

**Comment by syclik** [comment]
Thanks for the quick reply! I'll just update to `actions/checkout@v2`. Thanks!

**Comment by syclik** [comment]
Verified that v7.0.4 works without changing the file. Thank you.
