### ISSUE TITLE
Error on protected branch

### ISSUE THREAD

**Issue by oc-stephen-bennett** [phips28/gh-action-bump-version#161]
Hi, 

Im trying to semver tags on a protected master branch. I have the following setup:

master branch protection:
- require a pull request before merging
  - requre approvals
  -  require code owners
  -  allow specified actors to bypass required pull request ( myself)
  
  I created a PAT for myself and added that as a secret (BYPASS)

action looks like below: 

```
name: Push
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.BYPASS }}
        with:
          skip-tag: 'false'
```  

I have a CODEOWNERS file that is like below:

```
* @org/myself
! package.json
```

When i run the action i still get the error:

```
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✖  fatal     remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Waiting on code owner review from openc/devops.        
To https://github.com/openc/oc-github-repository.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/openc/oc-github-repository.git'

git exited with code 1
✖  fatal     Failed to bump version
```

Is there a work around to keep a master branch protected while enabling your action?

**Comment by phips28** [comment]
I only know where user used an admin user token to bypass all checks. But never used it myself.

**Comment by oc-stephen-bennett** [comment]
Hi, 

I am an admin on the org and gave the PAT full access, is that what you mean? or is there another PAT you can use?

**Comment by oc-stephen-bennett** [comment]
Sorry forgot i opened this, yes thats how i resolved it as well. though doing so did break other steps.
