### ISSUE TITLE
Allow for GitHub Action environment variable to set the name of package.json (ex. PACKAGEJSON_NAME)

### ISSUE THREAD

**Issue by jm-boop** [phips28/gh-action-bump-version#163]
A hypothetical repository would be one where there needs to be two package.json files in the same directory, so one would have an affix (ex. `package.some-affix.json`). It would be helpful to set a param (ex. `PACKAGEJSON_NAME: 'package.some-affix.json'`), where the index.js uses this name over the default 'package.json'.

**Comment by phips28** [comment]
happy to merge a PR when you create one.
