### ISSUE TITLE
Why my commit message is empty!

### ISSUE THREAD

**Issue by chaikuna** [phips28/gh-action-bump-version#170]

**Comment by chaikuna** [comment]
![image](https://user-images.githubusercontent.com/104134843/176163793-92b1116c-6aa3-43d0-bebb-314b13e3d463.png)

**Comment by chaikuna** [comment]
I try with https://github.com/phips28/gh-action-bump-version/blob/master/.github/workflows/push.yml

**Comment by phips28** [comment]
This says it did not find any commit messages in the current event.

Did you push to the master branch?

Just executing the action wont work properly!

**Comment by chaikuna** [comment]
It work only master branch?
this I try on my testing branch for prove it work

**Comment by chaikuna** [comment]
It work when I create new repo for test.
I will investigate.
Thank you.
