### ISSUE TITLE
Add release notes to version

### ISSUE THREAD

**Issue by Benwick91** [phips28/gh-action-bump-version#18]
I love the action. It works fine!

Now I want to add other release notes out of my commits and not only "ci: version bump to *.*.*".
Is this possible?
And another question:
If one commit in the process includes "major" and the current version is 0.9.5, the result is 7.0.0 Am I right?

Thanks for your help!

**Comment by phips28** [comment]
thx. 

1. thats currently not possible to customize the msg. but you can fork and create a pull request with customization option for that
2. major: 0.9.5 => 1.0.0 (minor: 0.9.5 => 0.10.0, patch: 0.9.5 => 0.9.6)

**Comment by Benwick91** [comment]
Thank you for the quick answer. I will see when I get time to fork and make a PR. :) 

I have two more questions. I hope this is ok:
1. I am using the action to test on push and it works without problems. Now I want to use it when pushing in master (so when the PR is merged). But the master, we work on, is protected. What will be the best way to do it?
2. The first time I want to use it with pushing in master the version wasn't bump, and it shows the message: 'No action necessary!'
Where does he check the commit messages? Because on push to the PR it works every time (even on the same branch)

Thank you!

**Comment by phips28** [comment]
1. I havent tested with protected branches, but it seems that it doesnt work for GH actions: https://github.community/t5/GitHub-Actions/How-to-push-to-protected-branches-in-a-GitHub-Action/td-p/29609/page/3

2. check the code here: https://github.com/phips28/gh-action-bump-version/blob/master/index.js
this might be the case that you already pushed the version in your PR, then merged to master and then your commit message includes 'version bump to' https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L17

**Comment by Benwick91** [comment]
Thank you! 

1. You're seem right. That's a pitty. It will be very helpful in an workflow with PRs and protected master. But that's not your fault. So I will not be able to use this charming action. 
I thought it could work with:   
```
env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_PUSH}}
```

But it doesn't work.
Thank you for your time :)

**Comment by Benwick91** [comment]
I now make a new workflow. I created a protected branch develop and opens the master. So my PRs goes into develop. And when develop is pushed into master, the version is bumped. Not the best way but it works. 

But now I think about one problem:
If one PR has a "major" and one has a "minor", and both are merged into develop and after that the whole develop is merged in master, what will be the new bumped version? We will see :D

**Comment by phips28** [comment]
the latest commit wins, thats how git works.
