### ISSUE TITLE
Can I use this on pushes that have multiple commits?

### ISSUE THREAD

**Issue by Noxillio** [phips28/gh-action-bump-version#181]
I would prefer if each individual commit resulted in the workflow being run, rather than every instance of "push", which can contain multiple commits, which can potentially ruin the purpose of this workflow.

If it's possible then please provide an example of how I can do this. I've seen that commands can be run for each commit but I'm not sure what exactly to do from there or how to actually apply this to that.

**Comment by phips28** [comment]
Can I use this on pushes that have multiple commits? YES

commit = local (you can commit 5 changes, and not pushing to remote)
push = github repo => then the action runs

**Comment by Noxillio** [comment]
Yeah but will the workflow run for each individual commit? That's what I'm looking for.
