### ISSUE TITLE
Do not use set-output command

### ISSUE THREAD

**Issue by josu-vergara-lecue** [phips28/gh-action-bump-version#190]
First of all, thanks a lot for keeping this repository up to date.

When running the `gh-action-bump-version` action, we are getting warnings of type:
_The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/_

I think that the culprit is [this](https://github.com/phips28/gh-action-bump-version/blob/3efc8c1af2812a17625921c250d9fc3c24a7ab17/index.js#L205) line, where `set-output` is being used. `set-output` has been deprecated as described in the link above, and starting 1st June 2023, invoking it will result in an error.

As mentioned in the link, this can be replaced using the Github core library (`@actions/core`) `setOutput` method, but as far as I can see this would be a new dependency for the project.

**Comment by josu-vergara-lecue** [comment]
Hi,

I have created a one-line fix by using a shell command. It is up to you to decide whether you are fine with that approach or whether you rather write directly to the file containing the environment variables.

**Comment by phips28** [comment]
fixed here: https://github.com/phips28/gh-action-bump-version/pull/192
thx
