### ISSUE TITLE
Support for tag suffixes

### ISSUE THREAD

**Issue by sbsrnt** [phips28/gh-action-bump-version#196]
Hi there!
I'm automating my electron app releases through `electron-builder` and I found this action to be extremely helpful as `electron-builder` publishes new release whenever there is a new version in `package.json`.

However I found some sort of limitation with automation when it comes to `alpha` or `beta` releases with `electron-builder`. While this package works wonderfully when `commit` message includes said keywords, it's less so impactful when the `tags` that are being created don't include `alpha` or `beta` keywords.

Would it be possible to add optional `tag suffix` with custom suffix 🤔?

**Comment by phips28** [comment]
Does prefix not fulfill your needs?
https://github.com/phips28/gh-action-bump-version#tag-prefix

**Comment by sbsrnt** [comment]
I would think that it would be _enough_ following the `electron-builder` [docs](https://www.electron.build/tutorials/release-using-channels.html#electron-builder)
> All you have to do to release using channels is to define the channel in the version tag of the package.json. Add “-beta” or “-alpha” (nothing for “latest”) to automatically build for the related channel.

But having `-beta` in the prefix would likely break SemVer convention thus leading to more problems with things like changelog generation and probably introduce other issues.

And on top of that `v-beta1.0.0` looks quite questionable but that can be considered as an opinion.
