### ISSUE TITLE
Issue with simultaneous Pull Requests

### ISSUE THREAD

**Issue by cerico** [phips28/gh-action-bump-version#207]
If two PR's are approved at the same time and an action for each is launched the second will fail saying the tag already exists

```
fatal: tag 'v2.0.9' already exists
```

Rerunning the action produces the same result

If the action for the first PR completes before the second PR starts its ok, but not if the PR's are approved too close together (and the actions initiated too close together).

**Comment by phips28** [comment]
But this also happens if 2 devs try to push the same version at the same time. 😉 its git not this action. Nothing I can fix here. 

Not sure if github has the possibility to only have one action running at a time. (Never heard of)
