### ISSUE TITLE
Build phips28/gh-action-bump-version/v8.0.18 Failing 

### ISSUE THREAD

**Issue by LS185230** [phips28/gh-action-bump-version#209]
Build Step Failing with the Following Error : 

![image](https://user-images.githubusercontent.com/84069643/234617836-57d9b0c5-9c16-4648-91ee-35dad88dc83b.png)

![image](https://user-images.githubusercontent.com/84069643/234618006-fa953a86-ef1c-4214-8f49-a13f3fbae5b5.png)

![image](https://user-images.githubusercontent.com/84069643/234618158-daa59cf7-c70f-43ef-9c6b-d8c212dc2510.png)

I believe this is a problem with the node:14.14-slim base image which is being used to build which is not able to fetch debiam amd 64 packages . 

Ref: https://unix.stackexchange.com/questions/743839/apt-get-update-failed-to-fetch-debian-amd64-packages-while-building-dockerfile-f

**Comment by rodiali-dig** [comment]
@LS185230 Update the action to the latest version, that should fix your issue. 
The latest version currently is v9.1.0 and you are on v8.0.18.
How to update? In your gh-action file, replace `uses: phips28/gh-action-bump-version@v8.0.18` with `uses: phips28/gh-action-bump-version@master`
