### ISSUE TITLE
receive working-directory prop for monorepo project

### ISSUE THREAD

**Issue by dfantonio** [phips28/gh-action-bump-version#21]
Recently I started using github actions to automate my pipeline and your action is really helpful to automatically update my version.
The problem I've found is that you don't use the working-directory param, only being able to update the package.json on the root of the repository.
Do you have any plans to implement this feature?

**Comment by phips28** [comment]
No plans so far as I dont have a usecase for that. but maybe you can create a PR or draw a better documentation what must be implemented. :)

**Comment by dfantonio** [comment]
After looking your code, I found a param called `PACKAGEJSON_DIR` that allowed me to specify a path. So I submitted a [PR](https://github.com/phips28/gh-action-bump-version/pull/22) with new documentation on this param.
