### ISSUE TITLE
Support pulling before pushing commits

### ISSUE THREAD

**Issue by tomchambers2** [phips28/gh-action-bump-version#210]
I have a monorepo with a number of packages. On push to the monorepo a number of actions run (where there are code changes). When the first version bump runs it adds a new commit, so the next version bump fails because there are commits ahead on the branch.

There seems to be a solution using skip-push and then doing a pull/push as another step, but it's a bit messy and it would be nice to integrate this into the action somehow. Would there be a harm in doing a pull before the push always?

**Comment by phips28** [comment]
afaik, we cant pull as we are running on a detached head, when we get the action trigger.
But never tested and wont implement it in the action myself as there is already a solution with the skip-push.
I am happy to accept a PR if you find a fix.
