### ISSUE TITLE
Please support to change the package.json filename

### ISSUE THREAD

**Issue by aditiaprasetio** [phips28/gh-action-bump-version#229]
https://github.com/phips28/gh-action-bump-version/blob/d84ee862bf54f45e75b2918b2ce1007d3fed25f1/index.js#L269

**Comment by phips28** [comment]
Why would you like to do that? afaik npm version ... always changes package.json and looks for it.

**Comment by phips28** [comment]
@aditiaprasetio you can provide a PR and I will merge if ok.
