### ISSUE TITLE
Add option to add --no-verify to git commit

### ISSUE THREAD

**Issue by davglass** [phips28/gh-action-bump-version#243]
We use the [`pre-commit`](https://www.npmjs.com/package/pre-commit) npm package to run lint and run tests prior to commit.

When using this action, we get double test runs as it also executes when this commits the tag. Would an option to add `--no-verify` to the git commit line be worth submitting a PR for?

**Comment by phips28** [comment]
yes provide a PR and I can merge

**Comment by BradyRyun** [comment]
I can take this.

**Comment by phips28** [comment]
thanks @BradyRyun 🙂  🚀
