### ISSUE TITLE
Any tags pushed from the Bumped version commit not triggering any github workflows.

### ISSUE THREAD

**Issue by laerdal-azhar** [phips28/gh-action-bump-version#246]
So we are using this to bump the version & commit in a repo & from this commit release tags to different env, these tags normally trigger github workflow from any other commit but just doesn't trigger the workflow from the bumped version commit.

Is this expected behaviour?

I have tried using Github App token with correct permissions & personal PAT token as well, doesn't work on both 

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          minor-wording: "feature"
          major-wording: "Breaking CHANGE,MAJOR"
          commit-message: "CI: Bump version to {{version}} [skip ci]"
          skip-tag: ${{ inputs.skip-tag }}
          bump-policy: "last-commit"
        env:
            #GITHUB_TOKEN: ${{ steps.write-app-token.outputs.token }}
            GITHUB_TOKEN: ${{ env.github_access_token}}

**Comment by phips28** [comment]
I remember someone had the same issue, but thats the expected behavior from github. An action-commit does not trigger another action.

**Comment by laerdal-azhar** [comment]
removing [skip ci] from the commit message fixed the issue that I was facing.
