### ISSUE TITLE
Output paring breaks due to unexpected outputs - add silent flag

### ISSUE THREAD

**Issue by yuvalshilo** [phips28/gh-action-bump-version#249]
Hey,
We are trying to use this action, but the parsing of the output of the command `npm version --git-tag-version=false patch`
can break in the function `parseNpmVersionOutput`
if there are lines in the output, after the version line
![image](https://github.com/phips28/gh-action-bump-version/assets/28350648/c64b0d3c-5d52-414f-90eb-eb6e87bcd4f9)
for example,
![image](https://github.com/phips28/gh-action-bump-version/assets/28350648/8d4e161e-92d1-47ed-bdb5-dbf43f89e504)

This can be easily fixed with no side effects with a simple --silent flag added.
If you want, I'll be happy to push PR if you'll grant me permissions :)

**Comment by phips28** [comment]
good idea, just create a PR and I review/merge.

**Comment by yuvalshilo** [comment]
> good idea, just create a PR and I review/merge.

@phips28 

I think the repo settings doesn't allow external users to create prs & branches:
<img width="874" alt="image" src="https://github.com/phips28/gh-action-bump-version/assets/28350648/c5015d41-639c-4f84-86a5-3c8851d9c53c">

**Comment by phips28** [comment]
you need to fork and then create a PR from your repo to this one. thats how it works for all open source projects on github.

**Comment by yuvalshilo** [comment]
Sorry about that, created a PR now. thanks
@phips28 
https://github.com/phips28/gh-action-bump-version/pull/250

**Comment by phips28** [comment]
thx
