### ISSUE TITLE
Option to add ***NO_CI*** to commit message from gh action, to avoid it triggers CI again

### ISSUE THREAD

**Issue by Casperhr** [phips28/gh-action-bump-version#27]

**Comment by phips28** [comment]
Can you create a PR for that? I am currently tight on time. should be a quick change to additionally add it.

**Comment by Jacse** [comment]
As far as I know, this [isn't supported for GitHub Actions](https://github.com/actions/runner/issues/774)

**Comment by mattanglin** [comment]
Created a PR to address this as [GitHub Actions recently added support for this](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)
