### ISSUE TITLE
No action necessary! when a bump should occur

### ISSUE THREAD

**Issue by jbolotin** [phips28/gh-action-bump-version#43]
Hi there, thanks for maintaining this great action!

We recently modified our flow to involve an intermediate branch that PRs are merged to before going to our main branch. Unfortunately, since doing this, this action has failed to automate our version bump. Instead, when we do a "Rebase and Merge" from the intermediate branch, we get the "No action necessary!" message from the action.

Not sure what's causing this or if you have any recommendations for how we might be able to resolve this. much appreciated!

**Comment by phips28** [comment]
Hi @jbolotin,
did the action run in the PR already? If so, there would be a commit message with '*version bump to*'
if the action finds this message in the commits, it stops:
https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L22

**Comment by jbolotin** [comment]
Hi @phips28 , thanks for the reply!

The action did not run in the PR in this case because the action is scheduled to only run on push to our main branch. Please let me know if I can provide any other info that me be of help in diagnosing this!

**Comment by phips28** [comment]
I've added a console.log to see what commit messages you get when it runs the action. https://github.com/phips28/gh-action-bump-version/blob/master/index.js#L22
Please try it again and post your log output here.

**Comment by jbolotin** [comment]
I believe this was caused by me not rebasing my intermediate branch after the version bump on the main branch occurred. Closing this for now because everything seems to be working when I do that, which should have been done previously anyways. Thanks for the help!
