### ISSUE TITLE
Docs suggestion

### ISSUE THREAD

**Issue by lazysergey** [phips28/gh-action-bump-version#45]
guys thanks for great package 🤘
I would mention in docs that it is required to put `env` with token in step params - was not obvious for me as I just started with github actions and I was getting 'incorrect name or password' error for quite a while today)

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by phips28** [comment]
Can you change it in the docs and file a PR please? :)

**Comment by bootsie123** [comment]
Changes merged. I think this issue can be closed now
