### ISSUE TITLE
Push version bump commit into repo is only possible when you also choose to push a tag for the new version

### ISSUE THREAD

**Issue by fafeichter** [phips28/gh-action-bump-version#48]
Hi, README says the following:

> - Push the bumped npm version in package.json back into the repo.
> - Push a tag for the new version back into the repo.

Since #37 the bumped npm version in package.json is only pushed back into the repo when you also want to push the tag for the new version back into the repo.

The bumped npm version should be pushed regardless of whether I want to push the tag for the new version.

~ Fabian :)

**Comment by phips28** [comment]
hi,

thx for that hint, can you create a PR? 

cc @Eomm as you created #37

**Comment by fafeichter** [comment]
Done.
