### ISSUE TITLE
NPM unable to find package-lock.json

### ISSUE THREAD

**Issue by bootsie123** [phips28/gh-action-bump-version#50]
[Logs.txt](https://github.com/phips28/gh-action-bump-version/files/5425488/Logs.txt)
Hi! So far this GitHub action has been fantastic what I need it for. Thanks for much! However, recently I've run into a problem. For some reason, I keep running into an issue when the Docker container tries installing the node modules via npm from `npm ci --only=production`.

I get the following error:

```
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
```

As far as I can tell the `package-lock.json` file is being copied over, so I'm not really sure what the issue is. I also have a fork of this project too and tried having NPM automatically recreate the `package-lock.json` file. That hasn't fixed the issue either. Any ideas on why this is happening all of a sudden? I'm assuming it's most likely a bad update with something, but I've been unable to pinpoint what exactly that would be. Thanks!

**Comment by jbolotin** [comment]
This just started occurring for me as well in the last ~30 min

**Comment by stephanrotolante** [comment]
verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'i',
0 verbose cli   '--only=production'
0 verbose cli ]
1 info using npm@7.0.2
2 info using node@v15.0.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session b0d6d348fd45e087
20 timing npm:load Completed in 15ms
21 timing arborist:ctor Completed in 1ms
22 timing idealTree Completed in 21ms
23 timing command:install Completed in 23ms
24 verbose stack RangeError: Maximum call stack size exceeded
24 verbose stack     at Node.get parent [as parent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:691:5)
24 verbose stack     at Node.get resolveParent [as resolveParent] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:949:17)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:956:32)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
24 verbose stack     at Node.resolve (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:958:28)
25 verbose cwd /
26 verbose Linux 4.9.184-linuxkit
27 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--only=production"
28 verbose node v15.0.0
29 verbose npm  v7.0.2
30 error Maximum call stack size exceeded
31 verbose exit 1




This is from the npm error log in the docker container

**Comment by stephanrotolante** [comment]
https://github.com/phips28/gh-action-bump-version/pull/52 This should resolve it. There is something up with the nodeJS 15 image.
