### ISSUE TITLE
Version bump action failing with "Cannot find module '/github/workspace/index.js'" error

### ISSUE THREAD

**Issue by Grendel** [phips28/gh-action-bump-version#53]
Hey guys - we use your build action across a bunch of our repos (thanks!) and they have all started failing in the last hour or so with the following error. I see you have recently merged a commit.

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/github/workspace/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by tre-dev** [comment]
Same here. Broke pipeline. :/

**Comment by bootsie123** [comment]
It seems to be working fine for me. Could you upload the full log file?

**Comment by phips28** [comment]
I reverted the changes in Dockerfile, except the slim.
https://github.com/phips28/gh-action-bump-version/pull/54

**Comment by tre-dev** [comment]
Yes, works again. Thanks!

**Comment by Grendel** [comment]
Works for me too. Thanks guys. I owe you a beer / coffee!

**Comment by phips28** [comment]
no worries :) 
and sorry for the breaking change!
