### ISSUE TITLE
How to control when to create Github Tags?

### ISSUE THREAD

**Issue by dcbacarro** [phips28/gh-action-bump-version#58]
I want to use this action for the workflow in repo. I just want to know if it is possible to control when to create or not create a github tag when a version is bumped.

**Comment by phips28** [comment]
Do you mean per Push or general turn off the github tag?
For the latter check `skip-tag`: https://github.com/phips28/gh-action-bump-version#usage

**Comment by dcbacarro** [comment]
Thanks, I did not see that. Have to read usage docs thoroughly. :)
