### ISSUE TITLE
Possibility to set prerelease identifier manually

### ISSUE THREAD

**Issue by aasen** [phips28/gh-action-bump-version#59]
Hi!

Thanks for creating this action!

In the workflow I'm working on I want to bump version after publishing a package, automatically forcing it to a prerelease. This works already, so that's good.

However, it would be nice to set the --preid option manually so its possible to have 2.0.3-alpha.0 instead of 2.0.3-0.

Example:
`prerelease --preid=alpha`

What do you think? Feasible?

**Comment by phips28** [comment]
have you checked this:
https://github.com/phips28/gh-action-bump-version/pull/47/files
there is such a possibility.

**Comment by aasen** [comment]
If I've read the code correctly, it still needs the commit message to contain the word. I was really asking for a way to set the preid not related to commit message.

Flow:
...
1. automated version bump to x.x.x
2. publish publish docker image
3. automated version bump to prerelease x.x.x-alpha.0
...

Maybe the use case is too marginal and specific, feel free to close the issue if so. It's really to prevent developers accidentally overwriting the latest published package in the phase after running this action.

**Comment by phips28** [comment]
You could probably add a new config var. are you able to do a PR for that?

Currently I have no time to work on this.

**Comment by aasen** [comment]
I can see what I can do.

Thanks for taking time to answer :)
