### ISSUE TITLE
Not defaulting to patch anymore

### ISSUE THREAD

**Issue by johanlajili** [phips28/gh-action-bump-version#65]
It seems in **8.0.15** this github action does not default to patch anymore.

If you do not provide a patch-wording, it sets the version to null, and then exits without bumping the version.

I made a PR that should fix this here: https://github.com/phips28/gh-action-bump-version/pull/64

**Comment by phips28** [comment]
thx for the PR :)

**Comment by johanlajili** [comment]
Sorry it looks like that PR did not fix it actually, bug is still hapening for me.
