### ISSUE TITLE
Version increment based on labels

### ISSUE THREAD

**Issue by averyanalex** [phips28/gh-action-bump-version#68]
Can you add feature to incriment fersion based on PR labels? For example, "patch", or "feature" or "breaking".

**Comment by steakeye-gitlive-test** [comment]
> Can you add feature to incriment fersion based on PR labels? For example, "patch", or "feature" or "breaking".

@averyanalex there's another action that already does this... https://github.com/marketplace/actions/match-pr-label with https://github.com/marketplace/actions/create-new-semantic-version will do what you want
