### ISSUE TITLE
Can this be generalized to work for non JS projects?

### ISSUE THREAD

**Issue by dycw** [phips28/gh-action-bump-version#75]
For example, Python users could have their `setup.py` or `pyproject.toml` bumped too.

**Comment by phips28** [comment]
I never worked with python, so not sure how bumping it works 😉  but in general it could be possible, to define a `lang: js|py|...` to know what bump to use.
You could create a PR for that.

**Comment by steakeye-gitlive-test** [comment]
> For example, Python users could have their `setup.py` or `pyproject.toml` bumped too.

@dycw Have you tried https://github.com/marketplace/actions/conventional-changelog-action ? Just came across it now and it seems to support TOML and pointing to arbitrary version files
