### ISSUE TITLE
Commit message when bump package.json versión has double quotes and breaks conventional commits checks

### ISSUE THREAD

**Issue by mob-suvee** [phips28/gh-action-bump-version#8]
When the script runs this instructions:

> index.js -> line 45

`await tools.runInWorkspace('git', ['commit', '-a', '-m', `"ci: ${commitMessage} ${newVersion}"`])`

> ...

> index.js -> line 55

`await tools.runInWorkspace('git', ['commit', '-a', '-m', `"ci: ${commitMessage} ${newVersion}"`])`

The final commit message contains double quotes -> "ci: version bump to v0.0.1".

I work in a project that runs the github app Semantic Pull Requests in the  CI, so that commit message is not a conventional commit due the double quotes.

**Comment by phips28** [comment]
@mob-suvee thats true. do you want to push a PR?

**Comment by mob-suvee** [comment]
Yes please, but i have no access to push into the repo.

**Comment by phips28** [comment]
you need to fork, then push into your own repo and then create a pull request :) 

or send me the code here and I merge it when I have time.

**Comment by mob-suvee** [comment]
How silly I am, sorry for that, I already did the pr :)

**Comment by phips28** [comment]
no problem ;) I merged it
