### ISSUE TITLE
NPM Package-Lock V2

### ISSUE THREAD

**Issue by broksonic21** [phips28/gh-action-bump-version#81]
We are finding that after phips28/gh-action-bump-version, even on latest tag, that the package-lock.json isn't fully updated when you use a package-lock V2 version (npm@7 or later). Is there a way to bump the npm version it runs with?

Specifically:

We end up in this state:

```
{
  "name": "project",
  "version": "1.2.16",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.2.15",
```

- the top "version" is updated to match the package.json version, but the null packages version is not.

So this means when you run `npm i` locally, it creates an updated package-lock.json to get the non-updated one up to date, causing excess commits and churn.

**Comment by phips28** [comment]
I never worked with package lock v2. 
how can I reproduce? or what commands would you use to bump a version (in a manual way) - then we can see if we can implement/automate this.

currently its just calling `npm version ...` that updates everything.

**Comment by broksonic21** [comment]
you must be on npm at version 6 (i.e. `npm install --global npm@6`, or else the default install) in your docker file.

If you run `npm install --global npm@latest` in the docker or (`npm install --global npm@7.6.3`), it would bump to 7.* and it would use package-lock v2 by default. A nice solve would be an optional parameter for npm version to install, default to whatever your current version is to avoid breaking change. I'll see if I can prototype up in a fork.

See https://github.blog/2021-02-02-npm-7-is-now-generally-available/ for more on the differences

**Comment by broksonic21** [comment]
Unfortunately, just doing in our own workflow script that calls phips28/gh-action-bump-version isn't enough, as you launch and create your own docker file - so needs to be in a forked version of your Docker. I'll PR up something shortly that supports it.

**Comment by broksonic21** [comment]
Unfortunately, to support this, we had to do it in the core docker file: see https://github.com/broksonic21/gh-action-bump-version/pull/1, which I can use for now.

Alternatively, you could do it with installing npm in the docker file, but I don't see a way to do that via configuration at the core workflow level (either to pass in which npm to use or which node to use)

**Comment by phips28** [comment]
@broksonic21 I am now using the new docker: `FROM node:15.12.0-slim`

And it also works for v1 packages, because they have their own version in it: `"lockfileVersion": 1,`

You can now try to switch if you want.

**Comment by havenchyk** [comment]
Hey @phips28 I use `"lockfileVersion": 2,` and because of npm@7 even when I clone your package and run `npm i`, package-lock.json is updated

![image](https://user-images.githubusercontent.com/1291032/135908015-5390de17-a7b5-42ed-8f2b-d02f6fe93623.png)

I know it's all about npm probably you shouldn't care, but afaik lockfileVersion 2 is a standard at the moment (I'm a yarn user last years).

Do you have an idea how to add support of lockfileVersion 2?

**Comment by havenchyk** [comment]
I created an initial PR, please take a look and share your opinion https://github.com/phips28/gh-action-bump-version/pull/132
