### ISSUE TITLE
Feature Request: Optional tag commit message

### ISSUE THREAD

**Issue by vodlogic** [phips28/gh-action-bump-version#85]
We have set the commit message of the version bump to include [skip-ci] which ensures that our main branch push workflow doesn't execute in a continuous loop when the package.json file with the new version is committed.

However Im finding that our downstream workflow that is triggered when the tag is created does not execute. I think this is because by default the same commit message including [skip-ci] is used when creating the tag.

This action should allow a tag commit message to be optionally specified to allow [skip-ci] to be removed and this trigger any downstream workflows.

**Comment by phips28** [comment]
can you provide a PR please? 🙂

**Comment by vodlogic** [comment]
Closing this issue as the change doesnt have the desired effect - see the PR comments for more info
