### ISSUE TITLE
`PACKAGEJSON_DIR` is being ignored if `package.json` exists in root.

### ISSUE THREAD

**Issue by CWSites** [phips28/gh-action-bump-version#89]
I'm using a monorepo setup and I have a `package.json` in the root directory, however that is not the one I want to bump. I have the following configuration set and when `cat ./package.json` runs it completely ignores the `PACKAGEJSON_DIR`.

```bash
jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 12

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: './libs/dot-components'
        with:
          tag-prefix: ''

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
```

**Comment by phips28** [comment]
can you try without leading `./` ? 

I dont use this myself, but maybe thats the problem when concatinating the path in this code:
```
// Change working directory if user defined PACKAGEJSON_DIR
if (process.env.PACKAGEJSON_DIR) {
  process.env.GITHUB_WORKSPACE = `${process.env.GITHUB_WORKSPACE}/${process.env.PACKAGEJSON_DIR}`
  process.chdir(process.env.GITHUB_WORKSPACE)
}

```

**Comment by phips28** [comment]
is there maybe an error from the `chdir`?

**Comment by CWSites** [comment]
No errors, tried it without `./` as well. I was able to get it to work by doing the following

```bash
      - name: 'cat libs/dot-components/package.json'
        run: cat ./libs/dot-components/package.json
```

**Comment by phips28** [comment]
its working? `cat` just prints the file?

**Comment by CWSites** [comment]
correct, as a side question before we did these actions we were already using the format `0.0.0-alpha.XX` is there a way to have it intelligently pick up from the current version number?

<img width="429" alt="Screen Shot 2021-04-27 at 3 17 34 PM" src="https://user-images.githubusercontent.com/1242102/116299431-b2eabe80-a76b-11eb-8d54-ad3a983ad38a.png">

**Comment by CWSites** [comment]
Oh I see what's going on here, the `cat` is printing the root `package.json` but the `PACKAGEJSON_DIR` is what controls what file is being written during the bump.
