### ISSUE TITLE
Version bump not working on 'workflow_run' event

### ISSUE THREAD

**Issue by tnario** [phips28/gh-action-bump-version#97]
I have two workflows, one is triggered on 'push' event and the other is triggered on 'workflow_run' event. The workflow that is triggered on 'workflow_run' event uses the version bump action, but the action won't detect any commits from the branch that was checked out. If I combine those two workflows into one and use the 'push' event, then everything works correctly.

### screenshots
<img width="581" alt="image" src="https://user-images.githubusercontent.com/48561079/119487577-3c3ce300-bd62-11eb-8987-3f8a8c0626e9.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/48561079/119487631-4f4fb300-bd62-11eb-95c9-de25d7acf4c0.png">

Can someone help or is this a bug?

**Comment by phips28** [comment]
I never used `workflow_run` event. But I guess that the `push` event includes all new pushed commits, and workflow_run does not. And therefore the action cannot find any commit messages in that event.

**Comment by tnario** [comment]
Would there be a fix for this? Because right now I feel that actions/checkout serves no useful purpose.

**Comment by phips28** [comment]
there is no fix. this action is for `push` and `merge` actions, not for `workflow_run`.
